language: php

sudo: false

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer install --dev --no-interaction
    
script:
    - ./vendor/bin/phpunit -c tests --coverage-clover=build/logs/clover.xml
    
matrix:
    fast_finish: true
