language: php

sudo: false

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - export IS_HHVM=$(phpenv version | grep "hhvm" > /dev/null; echo $?)
  - echo $IS_HHVM

install:
  - composer install --dev --no-interaction --ignore-platform-reqs
    
script:
  - ./vendor/bin/phpunit -c tests --coverage-clover=build/logs/clover.xml
    
after_script:
  - ./tests/upload_artefacts.sh
    
matrix:
    fast_finish: true
