<?php

namespace Fabiang\Msgfmt\Parser\Gettext\Lexer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 11:50:08.
 *
 * @coversDefaultClass Fabiang\Msgfmt\Parser\Gettext\Lexer\Token
 */
class TokenTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Token
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Token('test', 42, 'somevalue');
    }

    /**
     * @covers ::getType
     * @covers ::__construct
     */
    public function testGetType()
    {
        $this->assertSame('test', $this->object->getType());
    }

    /**
     * @covers ::getLine
     * @covers ::__construct
     */
    public function testGetLine()
    {
        $this->assertSame(42, $this->object->getLine());
    }

    /**
     * @covers ::getValue
     * @covers ::__construct
     */
    public function testGetValue()
    {
        $this->assertSame('somevalue', $this->object->getValue());
    }
}
